PROCESS_SECTIONS = [
    ("PROCESS LOG :: TEXT GENERATION STEPS", [
        "This page documents the method and selected outputs from the development process.",
    ]),

    ("1) Voice analysis (spaCy)", [
        "-- Clarissa stats -------------",
        "Mean sentence length: 20.6",
        "POS proportions: {'NOUN': 0.155, 'VERB': 0.155, 'ADJ': 0.064, 'ADV': 0.067, 'PRON': 0.158}",
        "Top lemmas: [('like', 15), ('love', 15), ('feel', 14), ('go', 14), ('party', 14), ('come', 11), ('stand', 11), ('old', 11), ('look', 10), ('little', 10)]",
        "",
        "-- Septimus stats -------------",
        "Mean sentence length: 19.6",
        "POS proportions: {'NOUN': 0.18, 'VERB': 0.16, 'ADJ': 0.058, 'ADV': 0.062, 'PRON': 0.132}",
        "Top lemmas: [('man', 16), ('look', 15), ('world', 12), ('like', 12), ('cry', 12), ('beauty', 10), ('dead', 9), ('lie', 9), ('hand', 8), ('kill', 7)]",
    ]),

    ("2) First Markov chain (baseline)", [
        "Goal: show 'voice' surface patterns without semantic steering.",
        "Inputs tested: TIME, FLOWER, WORLD",
        "",
        "-------------",
        "Prompt: time",
        "",
        "CLARISSA: She could see Peter out of Mulberry's with her little pink face pursed in enquiry.",
        "SEPTIMUS: He knew the meaning of the world itself is without meaning.",
        "",
        "-------------",
        "Prompt: flower",
        "",
        "CLARISSA: Clarissa had leant forward, taken his hand, patting his knee and, feeling as she turned and walked back towards Bond Street, annoyed, because it was possible to go out of their ordinary ways, partly the background, it was time to move, to go--but where?",
        "SEPTIMUS: there he was; still sitting alone on the lower shelf, then, gradually at the mantelpiece, with the jar of roses.",
        "",
        "-------------",
        "Prompt: world",
        "",
        "CLARISSA: The leaden circles dissolved in the triumph and the strange high singing of some aeroplane overhead was what she looked like, but felt herself a stake driven in at the other end of the moment.",
        "SEPTIMUS: I leant over the edge of the world, he said.",

    ]),

    ("3) Semantic expansion (vector-based)", [
        "Goal: steer generation using semantic neighbors of the user prompt (spaCy vectors + cosine similarity).",
        "Method: user word -> similar words -> keyword set -> biased selection from many Markov samples.",
        "",
"-------------",
        "Prompt: time",
        "",
        "Clarissa keywords: ['time', 'go', 'come', 'old', 'look', 'know', 'night', 'see', 'time']",
        "Septimus keywords: ['time', 'look', 'time', 'go', 'see', 'come', 'know', 'run', 'old']",
        "",
        "CLARISSA: Strange, she thought, waiting to cross, half the time she gave a party.",
        "SEPTIMUS: could see him staring at the time; He began, very cautiously, to open his eyes, to see a dog become a man!",
        "",
"-------------",
        "Prompt: flower",
        "",
        "Clarissa keywords: ['flower', 'flower', 'leaf', 'fall', 'grow']",
        "Septimus keywords: ['flower', 'flower', 'fern', 'leaf', 'fall', 'grow', 'begin', 'root']",
        "",
        "LARISSA: Arlington Street and Piccadilly seemed to chafe the very temper of her own part, it was now over.",
        "SEPTIMUS: A sparrow perched on the back of a fern.",
        "",
"-------------",
        "Prompt: world",
        "",
        "Clarissa keywords: ['world', 'life', 'dignity', 'earth', 'heavens', 'ordinary', 'monster', 'heaven', 'divine']",
        "Septimus keywords: ['world', 'world', 'life', 'revelation', 'society', 'universal', 'profound', 'harmony', 'mankind']",
        "",
        "CLARISSA: The leaden circles dissolved in the Indian Army--thank Heaven she had quite forgotten what she loved; life; London; this moment of June.",
        "SEPTIMUS: He lay very high, on the heights; the fugitive; the drowned sailor; the poet of the world seemed to say.",
    ]),
]
